"""
ClinicalBridge - core pipeline (NO-API).

Shared by `main.py` and `notebook/clinicalbridge_prototype.ipynb` so both use exactly the same
orchestration, validation, guard rails, and the 8-section Clinical Context Brief renderer.

API-ready design: the orchestrator runs agents through a pluggable provider. The default
`ManualOutputProvider` replays stored manual Claude outputs (no API key, no network); a future
`ClaudeAPIProvider` would call the real Claude API with the same prompts and context.

EDUCATIONAL PROTOTYPE. All data is fictional. Not a real clinical tool. No diagnoses. Clinician
review is always required.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent

try:
    import jsonschema
    HAVE_JSONSCHEMA = True
except ImportError:  # validation degrades gracefully if the package is absent
    HAVE_JSONSCHEMA = False

DISCLAIMER = (
    "EDUCATIONAL PROTOTYPE - all patient data is FICTIONAL. This is NOT a real clinical tool, it "
    "does NOT make diagnoses, and clinician review is ALWAYS required."
)

# Mapping from this project's internal urgency enum to the official COP-3442 brief taxonomy.
# The internal schema enum is left UNCHANGED (to keep all stored outputs/gold/evaluation valid);
# this map is used only for display/labeling and documentation.
URGENCY_TAXONOMY = {
    "emergent": "Critical",
    "urgent": "Urgent",
    "routine": "Routine",
    "monitor": "Informational",
}

# Critical-alert escalation message (no treatment advice, no diagnosis).
ESCALATION_MESSAGE = (
    "IMMEDIATE ESCALATION (Critical): this alert requires immediate human clinician review now. "
    "This prototype does not provide treatment advice or a diagnosis; route to a clinician or "
    "emergency pathway per local protocol."
)


def official_urgency(internal_level):
    """Map an internal urgency level to the official brief taxonomy label."""
    return URGENCY_TAXONOMY.get(internal_level, internal_level)


def is_critical(triage):
    """A triage result is Critical (escalation-worthy) when its internal urgency is 'emergent'."""
    return triage.get("urgency_level") == "emergent"


def escalation_notice(triage):
    """Return the escalation message if the triage is Critical, else None."""
    return ESCALATION_MESSAGE if is_critical(triage) else None


# --------------------------------------------------------------------------- #
# Loading
# --------------------------------------------------------------------------- #
def load_json(rel):
    with open(ROOT / rel, "r", encoding="utf-8") as f:
        return json.load(f)


def load_patients():
    return {p["patient_id"]: p for p in load_json("data/patients.json")["patients"]}


def load_schemas():
    return {sp.stem.replace(".schema", ""): json.loads(sp.read_text(encoding="utf-8"))
            for sp in (ROOT / "schemas").glob("*.json")}


SCHEMAS = load_schemas()


def scenario_index():
    idx = {}
    for sp in sorted((ROOT / "scenarios").glob("scenario_*.json")):
        sc = json.loads(sp.read_text(encoding="utf-8"))
        idx[sc["scenario_id"]] = sp
    return idx


SCENARIOS = scenario_index()


def load_scenario(sid):
    return json.loads(SCENARIOS[sid].read_text(encoding="utf-8"))


# --------------------------------------------------------------------------- #
# Agent providers (API-ready design)
#
# The orchestrator never talks to a model directly -- it asks a *provider* to run an
# agent. The DEFAULT provider replays stored manual Claude outputs (no API key, no
# network). A future ClaudeAPIProvider would instead send the agent's prompt + context
# to the Claude API. Swapping the provider is the only change needed to go live.
# --------------------------------------------------------------------------- #
class AgentProvider:
    """Interface: run one agent and return its JSON output."""

    def run_agent(self, agent_name, scenario_id, context=None):
        raise NotImplementedError


class ManualOutputProvider(AgentProvider):
    """DEFAULT (no-API) provider: load the stored manual Claude output for an agent.

    `context` is accepted for interface compatibility but is not needed here -- the
    output was already generated by hand in the Claude app and saved to agent_outputs/.
    """

    def run_agent(self, agent_name, scenario_id, context=None):
        return load_json(f"agent_outputs/scenario_{scenario_id}_outputs.json")[agent_name]


class ClaudeAPIProvider(AgentProvider):
    """Placeholder for a future live Claude API connection.

    Intentionally NOT implemented in this no-API prototype: it makes no network call and
    does NOT require the `anthropic` package. To enable Claude API mode later, implement
    `run_agent()` to send the agent's v3 prompt + `context` to Claude and return
    schema-valid JSON, then pass `provider=ClaudeAPIProvider()` to `run_pipeline()`.
    """

    def __init__(self, *args, **kwargs):
        # No client is created and no API key is read in the prototype.
        pass

    def run_agent(self, agent_name, scenario_id, context=None):
        raise NotImplementedError(
            "Claude API mode is not enabled in this no-API prototype. "
            "Implement ClaudeAPIProvider.run_agent() and pass provider=ClaudeAPIProvider() "
            "to run_pipeline() to connect a real Claude API."
        )


# The default provider keeps the project running with `python main.py` and no API key.
DEFAULT_PROVIDER = ManualOutputProvider()


def run_agent(agent_name, sid, context=None):
    """Backward-compatible helper; delegates to the default (manual) provider."""
    return DEFAULT_PROVIDER.run_agent(agent_name, sid, context)


# --------------------------------------------------------------------------- #
# Retrieval backend (the EHR Retrieval Agent's grounding source)
#
# The EHR Retrieval Agent is grounded by a real retrieval backend, abstracted here so the rest of
# the orchestration never changes. The DEFAULT backend is the GENUINE LangChain RAG pipeline
# (`langchain_pipeline`: EHR -> Document objects -> RecursiveCharacterTextSplitter -> local
# embeddings (all-MiniLM-L6-v2) -> FAISS -> retriever). If the LangChain stack is not installed,
# it degrades to the local pure-Python TF-IDF retriever (`rag_retrieval.py`) so the project still
# runs fully offline. Either way the retrieved evidence is attached to the agent context as the
# EHR Retrieval Agent's grounding documents (`context["ehr_retrieval_documents"]`).
# --------------------------------------------------------------------------- #
class RetrievalBackend:
    """Interface: build the clinical question and retrieve top-k grounding evidence."""

    name = "base"

    def clinical_question(self, scenario, triage=None):
        raise NotImplementedError

    def retrieve(self, question, patient_id, k=5):
        raise NotImplementedError

    def config(self):
        return {"backend": self.name}


class LangChainRetrievalBackend(RetrievalBackend):
    """GENUINE LangChain RAG backend (Document -> splitter -> embeddings -> FAISS -> retriever)."""

    name = "langchain"

    def __init__(self, embeddings_pref=None):
        import langchain_pipeline as lp  # may raise if the stack is not installed
        self._lp = lp
        self._pipeline = lp.get_pipeline(embeddings_pref=embeddings_pref)

    def clinical_question(self, scenario, triage=None):
        return self._lp.clinical_question_for_scenario(scenario, triage)

    def retrieve(self, question, patient_id, k=5):
        results = self._pipeline.retrieve(question, patient_id, k=k)
        # de-dupe by source_id (a split note can yield >1 chunk for the same source)
        seen, out = set(), []
        for r in results:
            sid = r["source_id"]
            if sid in seen:
                continue
            seen.add(sid)
            out.append({"source_id": sid, "source_type": r["source_type"], "score": r["score"],
                        "text": r["text"], "document": r["document"],
                        "patient_id": r["patient_id"], "scenario_id": r.get("scenario_id")})
        return out

    def config(self):
        c = dict(self._pipeline.config())
        c["backend"] = self.name
        return c


class LocalTfidfRetrievalBackend(RetrievalBackend):
    """DOCUMENTED fallback: the original local pure-Python TF-IDF retriever (no LangChain needed)."""

    name = "local_tfidf"

    def __init__(self):
        import rag_retrieval
        self._rr = rag_retrieval

    def clinical_question(self, scenario, triage=None):
        return self._rr.clinical_question_for_scenario(scenario)

    def retrieve(self, question, patient_id, k=5):
        results = self._rr.retrieve(question, patient_id, k=k)
        return [{"source_id": r["source_id"], "source_type": None, "score": r["score"],
                 "text": r["text"], "document": None, "patient_id": patient_id,
                 "scenario_id": None} for r in results]

    def config(self):
        return {"backend": self.name,
                "method": "pure-Python TF-IDF cosine (no embeddings, no vector DB, no API)"}


_RETRIEVAL_BACKEND = None


def get_retrieval_backend(prefer=None, force_rebuild=False):
    """Return the EHR retrieval backend: genuine LangChain if available, else local TF-IDF.

    prefer: None/"auto" -> LangChain if importable, otherwise the local TF-IDF fallback;
            "langchain" -> require LangChain (raise if unavailable);
            "local"/"tfidf" -> force the local fallback (e.g. fully-offline reproducibility check).
    """
    global _RETRIEVAL_BACKEND
    prefer = prefer or "auto"
    if _RETRIEVAL_BACKEND is not None and not force_rebuild and prefer == "auto":
        return _RETRIEVAL_BACKEND

    if prefer in ("local", "tfidf"):
        backend = LocalTfidfRetrievalBackend()
    elif prefer == "langchain":
        backend = LangChainRetrievalBackend()
    else:  # auto
        try:
            backend = LangChainRetrievalBackend()
        except Exception:
            backend = LocalTfidfRetrievalBackend()

    if prefer == "auto":
        _RETRIEVAL_BACKEND = backend
    return backend


def retrieve_ehr_evidence(sid, k=5, backend=None, triage=None, prefer=None):
    """Run the retrieval backend for a scenario; returns the EHR Retrieval Agent's grounding evidence.

    Returns {scenario_id, patient_id, question, k, results[], config, backend}. `results` is the
    ranked retrieved evidence (source_id, score, source_type, and the LangChain `document` when the
    LangChain backend is used). This is the single seam that grounds the EHR Retrieval Agent.
    """
    scenario = load_scenario(sid)
    pid = scenario["patient_id"]
    backend = backend or get_retrieval_backend(prefer=prefer)
    if triage is None:
        try:
            triage = run_agent("triage", sid)
        except Exception:
            triage = None
    question = backend.clinical_question(scenario, triage)
    results = backend.retrieve(question, pid, k=k)
    return {"scenario_id": sid, "patient_id": pid, "question": question, "k": k,
            "results": results, "config": backend.config(), "backend": backend.name}


# --------------------------------------------------------------------------- #
# Validation + guard rails
# --------------------------------------------------------------------------- #
def validate(obj, schema_name):
    if HAVE_JSONSCHEMA:
        jsonschema.validate(obj, SCHEMAS[schema_name])
    return True


def assert_consistent_patient(expected_pid, *agent_outputs):
    """Guard rail: every agent output must belong to the alert's patient."""
    for o in agent_outputs:
        pid = o.get("patient_id")
        if pid is not None and pid != expected_pid:
            raise ValueError(f"Patient ID mismatch: expected {expected_pid!r} but an agent output "
                             f"reported {pid!r}. Refusing to assemble a cross-patient brief.")


def run_pipeline(sid, provider=None, verbose=False, attach_retrieval=True,
                 retrieval_k=5, retrieval_backend=None, retrieval_prefer=None):
    provider = provider or DEFAULT_PROVIDER
    scenario = load_scenario(sid)
    pid = scenario["patient_id"]

    # `context` carries everything a future API provider would need to build a prompt.
    # The default ManualOutputProvider ignores it.
    context = {"scenario": scenario, "patient": load_patients().get(pid)}

    triage = provider.run_agent("triage", sid, context);   validate(triage, "triage_output")
    context["triage"] = triage

    # Critical-alert escalation: detected immediately after triage. In a real deployment this would
    # fire a notification without waiting for synthesis; here we flag it and still assemble context.
    escalation = escalation_notice(triage)

    # RETRIEVAL BACKEND (genuine LangChain RAG, or local TF-IDF fallback): retrieve the EHR evidence
    # for the triage-derived clinical question and attach the retrieved LangChain Documents to the
    # context that grounds the EHR Retrieval Agent. Fully guarded so it can never break the run.
    retrieval = None
    if attach_retrieval:
        try:
            retrieval = retrieve_ehr_evidence(sid, k=retrieval_k, triage=triage,
                                              backend=retrieval_backend, prefer=retrieval_prefer)
            context["ehr_retrieval"] = retrieval
            context["ehr_retrieval_query"] = retrieval["question"]
            # The retrieved LangChain Documents become the EHR Retrieval Agent's grounding context.
            context["ehr_retrieval_documents"] = [r["document"] for r in retrieval["results"]
                                                  if r.get("document") is not None]
        except Exception:
            retrieval = None  # never break the pipeline if retrieval is unavailable

    ehr    = provider.run_agent("ehr", sid, context);       validate(ehr, "ehr_retrieval_output")
    context["ehr"] = ehr
    anam   = provider.run_agent("anamnesis", sid, context); validate(anam, "anamnesis_output")
    context["anamnesis"] = anam
    brief  = provider.run_agent("brief", sid, context);     validate(brief, "clinical_context_brief")

    # guard rails
    assert_consistent_patient(pid, triage, ehr, anam, brief)
    assert brief.get("safety_disclaimer", "").strip(), "Brief missing safety disclaimer"
    assert brief.get("traceability_index"), "Brief missing traceability index"
    assert brief.get("missing_data_and_uncertainty"), "Brief missing uncertainty section"

    if verbose:
        tag = "  *** CRITICAL ESCALATION ***" if escalation else ""
        rtag = f" retrieval={retrieval['backend']}" if retrieval else ""
        print(f"Scenario {sid} ({scenario['name']}): OK - schemas valid, guard rails passed "
              f"[triage urgency={triage['urgency_level']} ({official_urgency(triage['urgency_level'])}) "
              f"validity={triage['alert_validity']}]{rtag}{tag}")
    return {"scenario": scenario, "triage": triage, "ehr": ehr, "anamnesis": anam,
            "brief": brief, "escalation": escalation, "retrieval": retrieval}


# --------------------------------------------------------------------------- #
# The 8-section Clinical Context Brief renderer
# Sections: 1 Alert Summary · 2 Patient Snapshot · 3 Contextual Analysis ·
#           4 Risk Assessment · 5 Recommended Actions · 6 Uncertainties and Gaps ·
#           7 Sources Used · 8 Safety Disclaimer
# --------------------------------------------------------------------------- #
REQUIRED_BRIEF_SECTIONS = [
    "1. Alert Summary", "2. Patient Snapshot", "3. Contextual Analysis", "4. Risk Assessment",
    "5. Recommended Actions", "6. Uncertainties and Gaps", "7. Sources Used", "8. Safety Disclaimer",
]


def render_brief(brief):
    ua = brief["urgency_assessment"]
    s = brief["patient_snapshot"]
    L = [f"# Clinical Context Brief  ({brief['brief_id']})",
         f"_Patient {brief['patient_id']} | Alert {brief['alert_id']} | {brief['generated_at']}_", ""]

    if ua.get("level") == "emergent":
        L.append(f"> **{ESCALATION_MESSAGE}**")
        L.append("")

    L.append("## 1. Alert Summary")
    L.append(brief["alert_summary"])

    L.append("\n## 2. Patient Snapshot")
    L.append(f"- Age / Sex: {s.get('age')} {s.get('sex')}")
    L.append(f"- Key conditions: {', '.join(s.get('key_conditions', [])) or '-'}")
    L.append(f"- Key medications: {', '.join(s.get('key_medications', [])) or '-'}")

    L.append("\n## 3. Contextual Analysis")
    for f in brief["contextual_findings"]:
        L.append(f"- {f['finding']}  _[{', '.join(f['citations'])}]_")

    L.append("\n## 4. Risk Assessment")
    L.append(f"- **Urgency (prioritization, NOT a diagnosis): {official_urgency(ua['level'])} "
             f"[official taxonomy]** (internal: {ua['level']}) - {ua['rationale']}")
    if brief["possible_contributing_factors"]:
        L.append("- Factors to consider (NOT diagnoses):")
        for p in brief["possible_contributing_factors"]:
            L.append(f"    - **{p['factor']}** - {p['supporting_evidence']}  _[{', '.join(p['citations'])}]_")
            L.append(f"        - uncertainty: {p['uncertainty']}")

    L.append("\n## 5. Recommended Actions (for clinician review - NOT orders)")
    for x in brief["suggested_clinician_considerations"]:
        L.append(f"- {x}")

    L.append("\n## 6. Uncertainties and Gaps")
    for c in brief.get("data_conflicts", []):
        L.append(f"- **Conflict:** {c['description']}  _[{', '.join(c['citations'])}]_")
    for m in brief["missing_data_and_uncertainty"]:
        L.append(f"- {m}")
    L.append(f"- Overall confidence: **{brief['overall_confidence']}**")

    L.append("\n## 7. Sources Used")
    for src, origin in sorted(brief["traceability_index"].items()):
        L.append(f"- `{src}` -> {origin}")

    L.append("\n## 8. Safety Disclaimer")
    L.append(f"> {brief['safety_disclaimer']}")
    return "\n".join(L)
